[global]
# Config file version
# mandatory field
# This field ties the config file syntax/format back to the collector version.
# This allows the collector to flag breaking changes where the config file needs to be updated.
# string optionally starting with "v"/"V" e.g., "v0.10", or "0.10"
version = "v0.19"

# Pluggable back end support
# Default configuration uses InfluxDB (v1)
stats_processor = "influxdb_plugin"
# The first three arguments are the host/IP, port and database for the InfluxDB database
# Optionally, pass the InfluxDB username and password as the fourth and fifth arguments, e.g.:
# localhost 8086 isi_data_insights influxdbuser influxdbpass
stats_processor_args = [ "localhost", "8086", "isi_data_insights" ]

# Prometheus collector support
# stats_processor = "prometheus_plugin"
# The port configuration has moved to the cluster section since it must be different for each cluster
# The optional first and second arguments are used for basic auth support
# stats_processor_args = []
# stats_processor_args = ["promuser", "prompass" ]

# Alternative back end which collects and discards the data (for testing)
# stats_processor = "discard_plugin"
# stats_processor_args = []

# If set to 0 or -1, authentication will be retried indefintely
# There is still an exponential backoff that is clamped to a maximum of
# 30 minutes.
# Default is still 8 retries. Uncomment the following line to retry forever
# max_retries = 0

# The min_update_interval_override param provides ability to override the
# minimum interval that the daemon will query for a set of stats. The purpose
# of the minimum interval, which defaults to 30 seconds, is to prevent
# the daemon's queries from putting too much stress on the cluster.
# The default value is 30 seconds.
# min_update_interval_override = 30

# If using prometheus, the collector supports the Prometheus "http SD" service
# discovery mechanism.
#
# The hostname/IP for the discovery service can be hard coded via listen_addr below
# otherwise the code will attempt to find and external public IP address
[prom_http_sd]
enabled = false
# listen_addr = "external_hostname"
sd_port = 9999


# clusters in this section are queried for all partitioned performance datasets
# the collector checks the dataset definition each collection period and handles
# additions, removals and definition changes without manual intervention
# Example definition:
# [[cluster]]
# hostname = "mycluster.xyz.com"
# username = "statsuser"
# password = "sekr1t"
# verify-ssl = false
# authtype = "basic-auth"
# disabled = false
# prometheus_port = 9090
#	...
[[cluster]]
hostname = "demo.cluster.com"
username = "root"
password = "a"
verify-ssl = true
